[build]
  base = "messenger-frontend"
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  VITE_API_URL = "https://finalprojectweb2.onrender.com/api"
  VITE_SOCKET_URL = "https://finalprojectweb2.onrender.com"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
